sudo: false

cache:
    directories:
        - $HOME/doxygen

before_script:
    # download doxygen 1.8.12
    - mkdir -p $HOME/doxygen
    - cd $HOME/doxygen
    - ls doxygen* >/dev/null 2>&1 || curl -L ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz | tar xz

script:
    - set -e
    - cd $TRAVIS_BUILD_DIR
    - python $TRAVIS_BUILD_DIR/.travis.d/definition_check.py
    - bash $TRAVIS_BUILD_DIR/.travis.d/download_sdk.sh
    - export VITASDK=$PWD/vitasdk
    - export PATH=$VITASDK/bin:$PATH
    - cd $VITASDK/arm-vita-eabi/include
    - rm -rf psp2 psp2kern vitasdk vitasdk.h
    - cd $VITASDK/arm-vita-eabi/lib
    - rm -rf *_stub.a
    - cd $TRAVIS_BUILD_DIR
    - cp -r include/* $VITASDK/arm-vita-eabi/include
    - vita-libs-gen db.yml output
    - cd output
    - make
    - cp *_stub.a $VITASDK/arm-vita-eabi/lib
    - cd $TRAVIS_BUILD_DIR
    - git clone https://github.com/vitasdk/samples
    - cd samples
    - for f in */Makefile; do make -C ${f%/*} all; done
before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"

deploy:
    provider: script
    overwrite: true
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis.d/deploy_docs.sh
    on:
        tags: false
        branch:
            - master
env:
    secure: ED1ZrDLS/z9A8JzO7N2HEkhd+sshiceMMehSPH0zLwrzGOlyMXZPuAX8zuyJ3qzAnixal0V+PKZU7Kfd3hJ6IUCrNj7ccNjynadkqmwA/WaFDV0cOpXwVw02/b88e580ZoJZ1NTA8bi7wz4oScUVGBqTKc+L9D3kjqNkQO114dckl/i4RgRPwvP5KJQdbzmgE+ShSG3/WEEZwqmOs0ZlkS4KtcK8xo5ZxxC60HRciCpwif7HHyrSpuWhHFIgfj9PqaXjfj94+5xT+jG7GHxlCAz5sCqtv/a4bSkJFlziEalShomoaouQbhGk3Vzy/lSVxuREFWdwS6BVXo44vjzvo0dkFKp0EC9l3yEyriOfI6tiW47vT6JlXvNJJhu3Qd345iXkJHBxbT9qvNnDpR1AknkWQng+qZFOlq6uI11hzNdgFmMnRRe7uaKw9Rg8Kc3iFEc7OsX8zKQ4W5tKap0XISvOrezEwghif8GHQpDAMdX7l2JQXjFs0qf9HNNbbW76h4pdYvspWrykxljCgiDWxvqteUsMhgO2Eby3VTM6rR7S5ZMh/3EdzztlcR0obNq6IUIf2S+F8EiOe+AlXf3j4rX/EsRToXBHldUCjIRLboZjVg2CI+vcNcVYCOaWtReUqUpWS2CD93OTcnq8a9giL5KNlIYzKjiB8jBn0PuWrRY=
